# 用户表
INSERT INTO tb_user (u_name, u_password, u_realname, u_email, u_phone, u_address, u_type)
VALUES ('admin', 'admin', '系统管理员', 'admin@admin.com', '15212345678', '河南郑州', '1'),
  ('zs', '123456', '张三', 'zs12ddd@member.com', '13612345679', '河南郑州', '1');

# 商品表
INSERT INTO tb_product(P_NAME,P_REAL_PRICE,P_NOW_PRICE,IS_STOCK,P_DESC,P_SIZE,P_COLOR,P_SCORE,P_TYPE_ID,
                       P_PIC_ID,P_PIC_URI)
VALUES ('【2罐】澳洲爱他美Aptamil金装婴幼儿奶粉4段（2岁以上）900g','339.00','300.00',1,'','900g','奶黄色粉末','4.8','');


# 商品类型表
INSERT INTO tb_pro_type(P_TYPE_NAME, P_TYPE_P_ID, MENU_URI, MENU_STYLE, IS_MENU)
VALUES ('淘宝商场', 0,'/shop/product-list.jsp', 4, 1),
  ('每日尝鲜', 0,'/shop/product-list.jsp', 4, 1),
  ('粮油调味', 0,'/shop/product-list.jsp', 4, 1),
  ('特产/进口商品', 0,'/shop/product-list.jsp', 4, 1),
  ('食品饮料', 0,'/shop/product-list.jsp', 4, 1),
  ('个人护理', 0,'/shop/product-list.jsp', 4, 1),
  ('母婴用品', 0,'/shop/product-list.jsp', 4, 1),
  ('家庭清洁', 0,'/shop/product-list.jsp', 4, 1),
  ('家具用品', 0,'/shop/product-list.jsp', 4, 1);
INSERT INTO tb_pro_type(P_TYPE_NAME, P_TYPE_P_ID, MENU_URI, IS_MENU)
VALUES ('奶粉', 1, '/shop/product-list.jsp', 1),
  ('宝宝食品', 1, '/shop/product-list.jsp', 1),
  ('宝宝洗护', 1, '/shop/product-list.jsp', 1),
  ('宝宝用品', 1, '/shop/product-list.jsp', 1),
  ('美妆护肤', 1, '/shop/product-list.jsp', 1),
  ('魅力彩妆', 1, '/shop/product-list.jsp', 1),
  ('食品保健', 1, '/shop/product-list.jsp', 1),
  ('生活电器', 1, '/shop/product-list.jsp', 1),
  ('厨房用具', 1, '/shop/product-list.jsp', 1),
  ('每日特价', 1, '/shop/product-list.jsp', 1),
  ('水果', 2, '/shop/product-list.jsp', 1),
  ('蔬菜', 2, '/shop/product-list.jsp', 1),
  ('肉类', 2, '/shop/product-list.jsp', 1),
  ('低温制品', 2, '/shop/product-list.jsp', 1),
  ('蛋、杂粮', 2, '/shop/product-list.jsp', 1),
  ('水产/海鲜', 2, '/shop/product-list.jsp', 1),
  ('豆制品', 2, '/shop/product-list.jsp', 1),
  ('熟食', 2, '/shop/product-list.jsp', 1),
  ('面包/早点', 2, '/shop/product-list.jsp', 1),
  ('生鲜套餐组合', 2, '/shop/product-list.jsp', 1),
  ('PRE奶粉', 9, '/shop/product-list.jsp', 1),
  ('1段奶粉', 9, '/shop/product-list.jsp', 1),
  ('2段奶粉', 9, '/shop/product-list.jsp', 1),
  ('3段奶粉', 9, '/shop/product-list.jsp', 1),
  ('4段奶粉', 9, '/shop/product-list.jsp', 1),
  ('5段奶粉', 9, '/shop/product-list.jsp', 1),
  ('1+段奶粉', 9,'/shop/product-list.jsp', 1),
  ('2+段奶粉', 9,'/shop/product-list.jsp', 1),
  ('成人奶粉', 9,'/shop/product-list.jsp', 1),
  ('肉泥', 10, '/shop/product-list.jsp', 1),
  ('果泥', 10, '/shop/product-list.jsp', 1),
  ('米粉', 10, '/shop/product-list.jsp', 1),
  ('维生素钙铁锌', 10, '/shop/product-list.jsp', 1),
  ('洗发沐浴', 11, '/shop/product-list.jsp', 1),
  ('宝宝护肤', 11, '/shop/product-list.jsp', 1),
  ('纸尿裤', 12, '/shop/product-list.jsp', 1),
  ('耳温枪', 12, '/shop/product-list.jsp', 1),
  ('奶瓶奶嘴', 12, '/shop/product-list.jsp', 1),
  ('护手霜', 13, '/shop/product-list.jsp', 1),
  ('眼霜', 13, '/shop/product-list.jsp', 1),
  ('洁面', 13, '/shop/product-list.jsp', 1),
  ('爽肤', 13, '/shop/product-list.jsp', 1),
  ('面部精华', 13, '/shop/product-list.jsp', 1),
  ('乳液', 13, '/shop/product-list.jsp', 1),
  ('面霜', 13, '/shop/product-list.jsp', 1),
  ('防晒霜', 13, '/shop/product-list.jsp', 1),
  ('护肤套装', 13, '/shop/product-list.jsp', 1),
  ('粉底', 14, '/shop/product-list.jsp', 1),
  ('睫毛膏', 14, '/shop/product-list.jsp', 1),
  ('眼线', 14, '/shop/product-list.jsp', 1),
  ('卸妆', 14, '/shop/product-list.jsp', 1),
  ('眉笔', 14, '/shop/product-list.jsp', 1),
  ('唇膏', 14, '/shop/product-list.jsp', 1),
  ('BB霜', 14, '/shop/product-list.jsp', 1),
  ('香水', 14, '/shop/product-list.jsp', 1),
  ('国产水果', 20, '/shop/product-list.jsp', 1),
  ('进口水果', 20, '/shop/product-list.jsp', 1),
  ('精选水果', 20, '/shop/product-list.jsp', 1),
  ('有机蔬菜', 21, '/shop/product-list.jsp', 1),
  ('精品蔬菜', 21, '/shop/product-list.jsp', 1),
  ('家畜', 22, '/shop/product-list.jsp', 1),
  ('家禽', 22, '/shop/product-list.jsp', 1),
  ('加工肉类', 22, '/shop/product-list.jsp', 1),
  ('野味', 22, '/shop/product-list.jsp', 1),
  ('厨房调味', 3, '/shop/product-list.jsp', 1),
  ('粮油', 3, '/shop/product-list.jsp', 1),
  ('干货', 3, '/shop/product-list.jsp', 1),
  ('方便速食', 3, '/shop/product-list.jsp', 1),
  ('核桃酥', 4, '/shop/product-list.jsp', 1),
  ('吸尘器', 8, '/shop/product-list.jsp', 1),
  ('方便面', 77, '/shop/product-list.jsp', 1),
  ('电脑数码', 1, '/shop/product-list.jsp', 1),
  ('代步机', 4, '/shop/product-list.jsp', 1);