CREATE DATABASE IF NOT EXISTS xhh DEFAULT CHARSET UTF8 COLLATE UTF8_GENERAL_CI;

USE xhh;

DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER(
 USER_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '用户编号',
 USER_NAME VARCHAR(30) NOT NULL UNIQUE COMMENT '登录名',
 USER_PASSWORD VARCHAR(30) NOT NULL UNIQUE COMMENT '登录密码',
 USER_REALNAME VARCHAR(20) NOT NULL COMMENT '真实姓名',
 USER_EMAIL VARCHAR(100) NOT NULL UNIQUE COMMENT '邮箱',
 USER_PHONE VARCHAR(20) UNIQUE COMMENT '手机号',
 USER_ADDRESS VARCHAR(100) NOT NULL COMMENT '地址',
 USER_TYPE TINYINT UNSIGNED NOT NULL COMMENT '用户类型 1:系统用户 0:注册会员用户',
 USER_STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态  2:锁定状态',
 CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
 CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
 UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
 UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
 PRIMARY KEY(USER_ID),
 KEY IDX_USER_U_NAME (USER_NAME),
 KEY IDX_USER_U_STATE (USER_TYPE)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 100 COMMENT='用户表';

DROP TABLE IF EXISTS TB_ADMIN;

CREATE TABLE TB_ADMIN(
 ADMIN_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '管理员编号',
 ADMIN_NAME VARCHAR(30) NOT NULL UNIQUE COMMENT '管理员名',
 ADMIN_PASSWORD VARCHAR(30) NOT NULL UNIQUE COMMENT '管理员登录密码',
 ADMIN_TYPE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '管理员类型 0:超级管理员 1:普通管理员',
 ADMIN_STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态  2:锁定状态',
 PRIMARY KEY (ADMIN_ID),
 KEY IDX_ADMIN_AD_NAME (ADMIN_NAME),
 KEY IDX_ADMIN_AD_STATE (ADMIN_STATE)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT='管理员表';

DROP TABLE IF EXISTS TB_ORDER;

CREATE TABLE TB_ORDER (
  ORDER_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '订单ID',
  USER_ID BIGINT UNSIGNED NOT NULL COMMENT '用户编号',
  ORDER_PRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '订单价格',
  ORDER_NAME VARCHAR (20) NOT NULL COMMENT '订单收货人',
  ORDER_ADDRESS VARCHAR (100) NOT NULL COMMENT '收货地址',
  ORDER_PHONE VARCHAR (20) NOT NULL COMMENT '收货人电话',
  ORDER_DESC VARCHAR (100) COMMENT '订单备注',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (ORDER_ID),
  KEY IDX_ORDER_U_ID (USER_ID),
  KEY IDX_ORDER_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT = '订单表';

DROP TABLE IF EXISTS TB_ORDER_DETAIL;

CREATE TABLE TB_ORDER_DETAIL (
  ODET_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '订单明细编号',
  ORDER_ID VARCHAR (20) NOT NULL COMMENT '订单编号',
  PRO_ID BIGINT UNSIGNED NOT NULL COMMENT '商品编号',
  PRO_NAME VARCHAR (50) NOT NULL COMMENT '商品名称',
  PRO_DESC VARCHAR (200) NOT NULL COMMENT '商品描述',
  PRO_SIZE VARCHAR (10) NOT NULL COMMENT '商品大小',
  PRO_COLOR VARCHAR (20) NOT NULL COMMENT '商品颜色',
  PRO_NUM TINYINT UNSIGNED NOT NULL COMMENT '商品数量',
  PRO_PRICE DOUBLE (9,2) UNSIGNED NOT NULL COMMENT '商品单价',
  ALL_PRICE DOUBLE (9,2) UNSIGNED NOT NULL COMMENT '订单总计',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (ODET_ID),
  KEY IDX_ORDER_DETAIL_USER_ID (ORDER_ID),
  KEY IDX_ORDER_DETAIL_PRO_ID (PRO_ID),
  KEY IDX_ORDER_DETAIL_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT = '订单明细表';

DROP TABLE IF EXISTS TB_PRODUCT;

CREATE TABLE TB_PRODUCT(
  PRO_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '商品编号',
  PRO_NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '商品名称',
  PRO_REAL_PRICE DOUBLE(9,2) UNSIGNED NOT NULL COMMENT '商品原价',
  PRO_NOW_PRICE DOUBLE (9,2) UNSIGNED NOT NULL COMMENT '商品现价',
  IS_STOCK TINYINT UNSIGNED NOT NULL COMMENT '是否有库存 1:有 0:无',
  PRO_DESC VARCHAR (200) NOT NULL COMMENT '商品描述',
  PRO_SIZE VARCHAR (50) NOT NULL COMMENT '商品大小',
  PRO_COLOR VARCHAR (50) NOT NULL COMMENT '商品颜色',
  PRO_SCORE DOUBLE(2,1) UNSIGNED NOT NULL COMMENT '评价分数',
  PRO_TYPE_ID BIGINT UNSIGNED NOT NULL COMMENT '商品类型ID',
  PRO_PIC_ID BIGINT UNSIGNED NOT NULL COMMENT '商品默认图片ID',
  PRO_PIC_URI VARCHAR (100) NOT NULL COMMENT '商品默认图片URL',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (PRO_ID),
  KEY IDX_PRODUCT_P_NAME (PRO_NAME),
  KEY IDX_PRODUCT_STATE (STATE)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT='商品表';

DROP TABLE IF EXISTS TB_PRO_TYPE;

CREATE TABLE TB_PRO_TYPE(
  TYPE_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT'商品类型ID',
  TYPE_NAME VARCHAR (50) NOT NULL COMMENT'商品类型名称',
  TYPE_P_ID BIGINT UNSIGNED NOT NULL COMMENT'商品类型父类编号',
  MENU_URI VARCHAR (100) COMMENT '菜单URL',
  MENU_STYLE TINYINT UNSIGNED COMMENT '菜单样式 1:平铺, 2:层级菜单, 3:图片, 4:仅链接',
  IS_MENU TINYINT UNSIGNED NOT NULL COMMENT ' 1:是菜单  0:不是菜单',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (TYPE_ID),
  KEY IDX_PRO_TYPE_NAME (TYPE_NAME),
  KEY IDX_PRO_TYPE_P_ID (TYPE_P_ID),
  KEY IDX_PRO_TYPE_STATE (STATE)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT='商品类型表';

DROP TABLE IF EXISTS TB_PRO_DETAIL;

CREATE TABLE TB_PRO_DETAIL(
  DET_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT'商品明细ID',
  PRO_ID BIGINT UNSIGNED NOT NULL COMMENT'商品编号',
  DET_LENGTH VARCHAR (10) NOT NULL COMMENT'商品长度',
  DET_HEIGHT VARCHAR (10) NOT NULL COMMENT'商品高度',
  DET_WIDTH VARCHAR (10) NOT NULL COMMENT'商品宽度',
  DET_MATYE VARCHAR (20) NOT NULL COMMENT'商品质量',
  DET_ADDRESS VARCHAR (20) NOT NULL COMMENT'商品产地',
  DET_DATE DATETIME NOT NULL COMMENT '生产日期',
  DET_DESC VARCHAR (500) NOT NULL COMMENT '详细介绍',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (DET_ID),
  KEY IDX_PRO_DETAIL_P_ID (PRO_ID),
  KEY IDX_PRO_DETAIL_STATE (STATE)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT='商品明细表';

DROP TABLE IF EXISTS TB_PRO_PIC;

CREATE TABLE TB_PRO_PIC (
  PIC_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '图片编号',
  PRO_ID BIGINT UNSIGNED NOT NULL COMMENT '商品编号',
  PIC_URI VARCHAR (100) NOT NULL COMMENT '图片URL',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (PIC_ID),
  KEY IDX_PRO_PIC_P_ID (PRO_ID),
  KEY IDX_PRO_PIC_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT = '商品图片表';


DROP TABLE IF EXISTS TB_PRO_COMMENT;

CREATE TABLE TB_PRO_COMMENT (
  COM_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '商品评论ID',
  PRO_ID BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  USER_ID BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  COM_TITLE VARCHAR (50) NOT NULL COMMENT '评论标题',
  COM_DESC VARCHAR (500) NOT NULL COMMENT '评论内容',
  PRO_SCORE DOUBLE UNSIGNED NOT NULL COMMENT '评价分数',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (COM_ID),
  KEY IDX_COM_USER_ID (USER_ID),
  KEY IDX_COM_PRO_ID (PRO_ID),
  KEY IDX_COM_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT = '商品评论表' ;

DROP TABLE IF EXISTS TB_CAR;

CREATE TABLE TB_CAR (
  CAR_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '购物车编号',
  USER_ID BIGINT UNSIGNED NOT NULL COMMENT '用户编号',
  PRO_ID BIGINT UNSIGNED NOT NULL COMMENT '商品编号',
  PRO_SIZE VARCHAR (10) NOT NULL COMMENT '产品大小',
  PRO_COLOR VARCHAR (20) NOT NULL COMMENT '产品颜色',
  PRO_NUM BIGINT UNSIGNED NOT NULL COMMENT '产品数量',
  PRO_PRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '产品单价',
  ALL_PRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '产品总价',
  STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态',
  CREATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '创建人ID',
  CREATE_DATE DATETIME DEFAULT NOW() COMMENT '创建时间',
  UPDATE_BY BIGINT UNSIGNED DEFAULT '1000' COMMENT '修改人ID',
  UPDATE_DATE DATETIME DEFAULT NOW() COMMENT '修改时间',
  PRIMARY KEY (CAR_ID),
  KEY IDX_CAR_U_ID (USER_ID),
  KEY IDX_CAR_P_ID (PRO_ID),
  KEY IDX_CAR_STATE (STATE)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT = '购物车表';

DROP TABLE IF EXISTS TB_NOTIFY_LOG;

CREATE TABLE TB_NOTIFY_LOG (
  SN BIGINT AUTO_INCREMENT COMMENT '日志ID',
  CMD_TYPE VARCHAR (100) NOT NULL COMMENT '操作类型',
  TABLE_NAME VARCHAR (100) NOT NULL COMMENT '表名',
  PK_VALUES VARCHAR (100) NOT NULL COMMENT '主键值',
  WHERE_CONDITION VARCHAR (100) NOT NULL COMMENT '条件',
  PRIMARY KEY(SN)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;